apiVersion: v1
kind: Service
metadata:
  name: demo-isolated-diagnostics
  namespace: demo-isolated
  labels:
    app.kubernetes.io/name: demo-isolated
    app.kubernetes.io/component: diagnostics-service
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: demo-isolated
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
